In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras


In [3]:
data = pd.read_csv('train_dataset.csv')

In [5]:
data.head()

ID  N_Days Status  ... Platelets  Prothrombin Stage
0  7135    1654     CL  ...     293.0         10.2   4.0
1  7326      41      C  ...     308.0         10.8   1.0
2  7254     297      D  ...     194.0         10.3   3.0
3  3135    1872      C  ...       NaN         10.5   4.0
4  2483     939     CL  ...     306.0         11.4   2.0

[5 rows x 20 columns]

In [6]:
#data.isna().sum()

In [7]:
data1 = data.drop(['ID','N_Days','Drug','Age','Sex','Ascites','Hepatomegaly','Spiders','Edema','Status'],axis = 1)

In [8]:
data1.head()

Bilirubin  Cholesterol  Albumin  ...  Platelets  Prothrombin  Stage
0        0.3        279.0     2.96  ...      293.0         10.2    4.0
1        0.3          NaN     2.96  ...      308.0         10.8    1.0
2        0.3        328.0     2.64  ...      194.0         10.3    3.0
3        0.3        302.0     2.02  ...        NaN         10.5    4.0
4        0.5        344.0     3.11  ...      306.0         11.4    2.0

[5 rows x 10 columns]

In [9]:
data1.shape


(6800, 10)

In [10]:
data1.replace(r'^\s*$', np.nan, regex=True) #replacing white spaces to NaN

Bilirubin  Cholesterol  Albumin  ...  Platelets  Prothrombin  Stage
0           0.3        279.0     2.96  ...      293.0         10.2    4.0
1           0.3          NaN     2.96  ...      308.0         10.8    1.0
2           0.3        328.0     2.64  ...      194.0         10.3    3.0
3           0.3        302.0     2.02  ...        NaN         10.5    4.0
4           0.5        344.0     3.11  ...      306.0         11.4    2.0
...         ...          ...      ...  ...        ...          ...    ...
6795        0.9        360.0     2.43  ...      314.0         12.9    1.0
6796        0.3          NaN     2.99  ...      399.0         10.6    4.0
6797        0.3        218.0     2.79  ...      103.0          9.3    1.0
6798        0.3          NaN     1.96  ...      354.0         10.6    2.0
6799        5.9          NaN     3.65  ...      288.0         11.1    4.0

[6800 rows x 10 columns]

In [11]:
data_final = data1.fillna(data1.mean())

In [12]:
data_final

Bilirubin  Cholesterol  Albumin  ...   Platelets  Prothrombin  Stage
0           0.3   279.000000     2.96  ...  293.000000         10.2    4.0
1           0.3   294.575831     2.96  ...  308.000000         10.8    1.0
2           0.3   328.000000     2.64  ...  194.000000         10.3    3.0
3           0.3   302.000000     2.02  ...  293.306097         10.5    4.0
4           0.5   344.000000     3.11  ...  306.000000         11.4    2.0
...         ...          ...      ...  ...         ...          ...    ...
6795        0.9   360.000000     2.43  ...  314.000000         12.9    1.0
6796        0.3   294.575831     2.99  ...  399.000000         10.6    4.0
6797        0.3   218.000000     2.79  ...  103.000000          9.3    1.0
6798        0.3   294.575831     1.96  ...  354.000000         10.6    2.0
6799        5.9   294.575831     3.65  ...  288.000000         11.1    4.0

[6800 rows x 10 columns]

In [13]:
data_final.isna().sum()

Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
dtype: int64

In [14]:
dataset = data_final.values #to create it as array

In [15]:
dataset

array([[3.00000000e-01, 2.79000000e+02, 2.96000000e+00, ...,
        2.93000000e+02, 1.02000000e+01, 4.00000000e+00],
       [3.00000000e-01, 2.94575831e+02, 2.96000000e+00, ...,
        3.08000000e+02, 1.08000000e+01, 1.00000000e+00],
       [3.00000000e-01, 3.28000000e+02, 2.64000000e+00, ...,
        1.94000000e+02, 1.03000000e+01, 3.00000000e+00],
       ...,
       [3.00000000e-01, 2.18000000e+02, 2.79000000e+00, ...,
        1.03000000e+02, 9.30000000e+00, 1.00000000e+00],
       [3.00000000e-01, 2.94575831e+02, 1.96000000e+00, ...,
        3.54000000e+02, 1.06000000e+01, 2.00000000e+00],
       [5.90000000e+00, 2.94575831e+02, 3.65000000e+00, ...,
        2.88000000e+02, 1.11000000e+01, 4.00000000e+00]])

In [16]:
dataset.shape

(6800, 10)

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X = data_final.drop(['Stage'],axis=1).values
y = data_final['Stage'].values


In [18]:
print(X.shape)
print(y.shape)

(6800, 9)
(6800,)


In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,shuffle = True)


In [20]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
X_train

array([[-4.68109548e-01, -1.60816661e-03, -7.20656237e-02, ...,
         3.00713270e-03, -4.12084199e-01, -1.24379759e-01],
       [-2.82528228e-01, -1.60816661e-03, -3.89928403e-01, ...,
        -1.26997167e+00,  1.24190661e+00, -1.02396313e+00],
       [ 1.81425071e-01, -1.60816661e-03,  7.31940229e-01, ...,
        -2.79673045e+00, -1.16794022e+00, -2.14338096e-01],
       ...,
       [-4.68109548e-01, -1.44208557e+00,  8.81522713e-01, ...,
        -2.08054038e-02, -1.68370079e+00,  5.55369149e-02],
       [-4.68109548e-01, -1.18032495e+00,  2.64494966e-01, ...,
         3.50461940e+00,  1.02848845e+00,  3.25411926e-01],
       [-4.06249108e-01,  5.51851841e-02, -2.77741539e-01, ...,
         3.00713270e-03,  2.90417276e-01,  6.85245273e-01]])

In [22]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(5440, 9) (1360, 9) (5440,) (1360,)


In [23]:
y_train

array([4., 2., 3., ..., 1., 2., 4.])

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
y_train =np.array([ x-1 for x in y_train])
y_test = np.array([ x-1 for x in y_test])

In [26]:
y_train

array([3., 1., 2., ..., 0., 1., 3.])

In [27]:
y_test

array([3., 3., 1., ..., 1., 3., 3.])

In [28]:

y_train = tf.one_hot(y_train,depth =4 , axis=0)
y_test = tf.one_hot(y_test,depth = 4,axis =0 )

In [29]:
y_train

<tf.Tensor: shape=(4, 5440), dtype=float32, numpy=
array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], dtype=float32)>

In [30]:
y_test

<tf.Tensor: shape=(4, 1360), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 1., 1.]], dtype=float32)>

In [31]:

print(y_train.shape)
print(y_test.shape)

(4, 5440)
(4, 1360)


In [32]:
y_train_size = y_train.shape[1]
y_test_size = y_test.shape[1]
print(y_train_size)
print(y_test_size)
y_train = np.transpose(y_train)
y_test = np.transpose(y_test)

5440
1360


In [33]:
print(y_train.shape)
print(y_test.shape)

(5440, 4)
(1360, 4)


In [34]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

model = Sequential([
    Dense(32, activation='relu', input_shape=(9,)),
    Dense(64, activation='relu'),
    Dense(64, activation='relu'),
    Dense(16, activation='relu'),
    Dense(4,activation = tf.nn.softmax)
])

In [35]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                320       
                                                                 
 dense_1 (Dense)             (None, 64)                2112      
                                                                 
 dense_2 (Dense)             (None, 64)                4160      
                                                                 
 dense_3 (Dense)             (None, 16)                1040      
                                                                 
 dense_4 (Dense)             (None, 4)                 68        
                                                                 
Total params: 7,700
Trainable params: 7,700
Non-trainable params: 0
_________________________________________________________________


In [37]:
prediction = model.fit(X_train, y_train,
              epochs=2000)

Epoch 1/2000
170/170 [==============================] - 5s 4ms/step - loss: 1.2148 - accuracy: 0.5055
Epoch 2/2000
170/170 [==============================] - 1s 5ms/step - loss: 1.1798 - accuracy: 0.5164
Epoch 3/2000
170/170 [==============================] - 1s 6ms/step - loss: 1.1733 - accuracy: 0.5164
Epoch 4/2000
170/170 [==============================] - 1s 5ms/step - loss: 1.1686 - accuracy: 0.5164
Epoch 5/2000
170/170 [==============================] - 1s 4ms/step - loss: 1.1647 - accuracy: 0.5164
Epoch 6/2000
170/170 [==============================] - 1s 4ms/step - loss: 1.1612 - accuracy: 0.5171
Epoch 7/2000
170/170 [==============================] - 0s 3ms/step - loss: 1.1560 - accuracy: 0.5162
Epoch 8/2000
170/170 [==============================] - 0s 3ms/step - loss: 1.1557 - accuracy: 0.5162
Epoch 9/2000
170/170 [==============================] - 0s 3ms/step - loss: 1.1484 - accuracy: 0.5173
Epoch 10/2000
170/170 [==============================] - 0s 3ms/step - loss: 1.145

In [38]:
model.evaluate(X_test,y_test, verbose=2)

43/43 - 0s - loss: 12.0246 - accuracy: 0.3765 - 299ms/epoch - 7ms/step


[12.024575233459473, 0.3764705955982208]

In [39]:
data = pd.read_csv('test_dataset.csv')

In [ ]:
data.head()

ID  N_Days Status             Drug    Age Sex Ascites Hepatomegaly  \
0  3870      41      C          Placebo  22553   F       N          NaN   
1  3462    1811      C  D-penicillamine  16223   F       N            Y   
2  1632     954      C  D-penicillamine  27100   F       N            N   
3   722    1969      D          Placebo  17039   F       N            Y   
4  1000    2721      D  D-penicillamine  17738   F     NaN          NaN   

  Spiders Edema  Bilirubin  Cholesterol  Albumin  Copper  Alk_Phos    SGOT  \
0       N     N        1.4        247.0     3.62     NaN       NaN  108.65   
1       N     N        0.3        311.0     2.80    92.0    1748.1     NaN   
2       N     N        0.4          NaN     3.56     NaN       NaN   43.52   
3       N     N        1.2          NaN     3.16     NaN     617.1  113.76   
4     NaN     N        3.2          NaN     2.36    89.0    1782.4     NaN   

   Tryglicerides  Platelets  Prothrombin  
0            NaN      169.0         11.6  
1          129.0      321.0         11.5  
2            NaN      296.0         10.3  
3            NaN      125.0         10.9  
4          129.0      138.0         10.6

In [40]:
data.shape

(3200, 19)

In [41]:
data.isna().sum()

ID                  0
N_Days              0
Status              0
Drug              963
Age                 0
Sex                 0
Ascites          1087
Hepatomegaly     1102
Spiders          1200
Edema               0
Bilirubin           0
Cholesterol      1435
Albumin             0
Copper           1006
Alk_Phos         1168
SGOT              987
Tryglicerides    1286
Platelets         164
Prothrombin        64
dtype: int64

In [42]:
data1= data.drop(['ID','N_Days','Drug','Age','Sex','Ascites','Hepatomegaly','Spiders','Status','Edema'],axis = 1)
#data1.replace(r'^\s*$', np.nan, regex=True)
#data_final = data1.drop(['Status','Edema'],axis = 1)
data1

                             

Bilirubin  Cholesterol  Albumin  ...  Tryglicerides  Platelets  Prothrombin
0           1.4        247.0     3.62  ...            NaN      169.0         11.6
1           0.3        311.0     2.80  ...          129.0      321.0         11.5
2           0.4          NaN     3.56  ...            NaN      296.0         10.3
3           1.2          NaN     3.16  ...            NaN      125.0         10.9
4           3.2          NaN     2.36  ...          129.0      138.0         10.6
...         ...          ...      ...  ...            ...        ...          ...
3195        0.3          NaN     2.75  ...            NaN      563.0         10.9
3196        4.7        422.0     4.30  ...          166.0        NaN         10.2
3197        0.8        408.0     3.56  ...          131.0      234.0         11.6
3198       15.3        258.0     3.21  ...          130.0      110.0         10.3
3199        0.3          NaN     3.42  ...          126.0      103.0         10.8

[3200 rows x 9 columns]

In [43]:
dataset = data1.fillna(data_final.mean())
print(dataset.isna().sum())
dataset = dataset.values

test_new = dataset
print(test_new.shape)

Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
dtype: int64
(3200, 9)


In [44]:
test_new

array([[1.40000000e+00, 2.47000000e+02, 3.62000000e+00, ...,
        1.33857823e+02, 1.69000000e+02, 1.16000000e+01],
       [3.00000000e-01, 3.11000000e+02, 2.80000000e+00, ...,
        1.29000000e+02, 3.21000000e+02, 1.15000000e+01],
       [4.00000000e-01, 2.94575831e+02, 3.56000000e+00, ...,
        1.33857823e+02, 2.96000000e+02, 1.03000000e+01],
       ...,
       [8.00000000e-01, 4.08000000e+02, 3.56000000e+00, ...,
        1.31000000e+02, 2.34000000e+02, 1.16000000e+01],
       [1.53000000e+01, 2.58000000e+02, 3.21000000e+00, ...,
        1.30000000e+02, 1.10000000e+02, 1.03000000e+01],
       [3.00000000e-01, 2.94575831e+02, 3.42000000e+00, ...,
        1.26000000e+02, 1.03000000e+02, 1.08000000e+01]])

In [45]:


target = model.predict(test_new)
target.shape

(3200, 4)

In [46]:
print(target[0])


[0. 0. 1. 0.]


In [47]:
index = tf.argmax(target, axis=0)

In [48]:
decoded = tf.argmax(target, axis=1)

In [49]:
target = np.array(decoded)
add = np.array([1])

In [50]:
target = target + add

In [51]:
print(target.shape)

(3200,)


In [52]:
np.unique(target)

array([1, 2, 3, 4])

In [53]:
print(target[144])

4


In [54]:
predictions = target

In [55]:
test_new = pd.DataFrame(test_new)

In [56]:
'''res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
print(res)

res.index = test_new.index # its important for comparison. Here "test_new" is your new test dataset
res.columns = ["Stage"]
res.to_csv("prediction_results2.csv", index = False)'''

'res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data\nprint(res)\n\nres.index = test_new.index # its important for comparison. Here "test_new" is your new test dataset\nres.columns = ["Stage"]\nres.to_csv("prediction_results2.csv", index = False)'

In [59]:
res = pd.DataFrame(predictions) #preditcions are nothing but the final predictions of your model on input features of your new unseen test data
res.index = test_new.index # its important for comparison. Here "test_new" is your new test dataset
res.columns = ["Stage"]

# To download the csv file locally
from google.colab import files
res.to_csv('prediction_results.csv')         
files.download('prediction_results.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>